### ISSUE TITLE
Max number of disks per node (VM) and k8s behaviour

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#1]
There is a limit to the number of disks ovirt can attach to a VM and this issue is to track few relevant points.

First, from k8s deployment pov, what happens when the driver fails to attach a drive because of specifically hitting ovirt maximum? Does the pod gets rescheduled to a different node? will it retry, with some incremental back-off,  flexvolume driver doesn't have other error codes than 1 or Failure. 

Second: what can we do from ovirt side to extend the max, add more scsi controllers etc.

Resources:
A single virtio-scsi controller supports 256 targets, [with up to 16384 SCSI logical units (LUNs) per target](https://www.mail-archive.com/qemu-devel@nongnu.org/msg443862.html)

**Comment by rgolangh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle max number of disks failure?](https://trello.com/c/oRlznR8K/26-handle-max-number-of-disks-failure)

**Comment by rgolangh** [comment]
This can be summarized to a doc under /doc folder

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
