### ISSUE TITLE
FailedAttachVolume event during pod creation

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-openshift-extensions#100]
**Description**
When creating a pod, FailedAttachVolume event with Warning severity is found. The pod is stuck in ContainerCreating status and never gets created.

**Steps To Reproduce**
1. Have ovirt-openshift-extensions installed
2. Create this StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ovirt
provisioner: ovirt-volume-provisioner
parameters:
  ovirtStorageDomain: "ocponrhv"
  fsType: "ext4"
```
Note: I tried providing `ovirtDiskThinProvisioning: "true"` and omitting it as well and the issue occurs in both scenarios.
3. Create this PVC:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mediawiki-data-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: ovirt
spec:
  storageClassName: ovirt
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
4. Create this pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: ovirt
spec:
  containers:
  - image: busybox
    name: test-pod
    command: ["sh", "-c", "while true; do ls -la /data; sleep 2; done"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: pv0002
      mountPath: "/data"
  volumes:
  - name: pv0002
    persistentVolumeClaim:
      claimName: mediawiki-data-disk
```
5. Check events on the pod by running `oc describe pod/test-pod | tail`. This is what I get:
```
Events:
  Type     Reason              Age               From                                              Message
  ----     ------              ----              ----                                              -------
  Normal   Scheduled           7m                default-scheduler                                 Successfully assigned default/test-pod to 10-37-139-4.rhev.lab.eng.brq.redhat.com
  Warning  FailedAttachVolume  1m (x11 over 7m)  attachdetach-controller                           AttachVolume.Attach failed for volume "pvc-ac2afc8d-1036-11e9-8894-001a4aa63068" : invalid character 'V' looking for beginning of value
  Warning  FailedMount         1m (x3 over 5m)   kubelet, 10-37-139-4.rhev.lab.eng.brq.redhat.com  Unable to mount volumes for pod "test-pod_default(bd9062ce-1036-11e9-8894-001a4aa63068)": timeout expired waiting for volumes to attach or mount for pod "default"/"test-pod". list of unmounted volumes=[pv0002]. list of unattached volumes=[pv0002 default-token-82qfn]
```

**Versions:**
 - Openshift|kubernetes versions: openshift v3.11.51, kubernetes v1.11.0+d4cacc0
- ovirt-flexvolume-driver: 0.3.2.1-45.ged00630

**Logs:**
- oc logs ovirt-volume-provisioner-bff6ffb45-fq8d7: http://pastebin.test.redhat.com/690964
- oc describe pod/test-pod: http://pastebin.test.redhat.com/690965

**Comment by rgolangh** [comment]
See the logs of the master controller:
```console
$ oc logs -n kube-system master-controllers-SPECIFIC-NAME-HERE 
```

What you should see is the exact error, as returned by the call to attach the disk to the compute VM.

I think what happens is the attach fails because the VM name is wrong. The attach operation is executed by the master who call the flexvolume-driver on the node that runs the pod. If the node name is not equal to the VM name in oVirt, then this will happen. 

The vm name being used for the attach is read from  **ovirtVmName** config entry for the flexvolume-driver. Go to your node and check:
```console
[root@1.1.1.1 ~]# cat /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ovirt~ovirt-flexvolume-driver/ovirt-flexvolume-driver.conf 
url=https://engine-fqdn/ovirt-engine/api
username=a@b
password=pass
insecure=True
cafile=
ovirtVmName=the-vm-name

```

**Comment by jan-zmeskal** [comment]
Hi Roy, you were probably right in your assessment. This is what can be found in the log in master-controllers-* pod: http://pastebin.test.redhat.com/692845

And indeed, the attribute `ovirtVmName` in ovirt-flexvolume-driver.conf has a wrong entry. Instead of holding oVirt VM name of a compute node, it holds oVirt FQDN of master0 node. 

I don't know what was the behaviour in the previous versions, because I've never checked that. But some change has probably been introduced, since I have not run into this problem before in the same scenario.

**Comment by rgolangh** [comment]
Here is some more info: during the deployment of the flex driver on each node, I take the node name, as identified by openshift (oc get nodes for example) and and I pass that as an ENV variable:
 https://github.com/oVirt/ovirt-openshift-extensions/blob/ed006305555c236c56b8881bf8b5f954a7b5c94a/deployment/ovirt-flexvolume-driver-apb/roles/provision-ovirt-flexvolume-driver-apb/tasks/main.yml#L59

Later on I use that use the ENV variable to write the ovirt-flexvolume-driver.conf:
https://github.com/oVirt/ovirt-openshift-extensions/blob/ed006305555c236c56b8881bf8b5f954a7b5c94a/deployment/ovirt-flexvolume-driver/entrypoint.sh#L18

It is a hard requirement to make sure the compute node name is the same as the VM name.
To make it more configurable I can try to take the VM name from a lable on the node(way back this was plan), say ovirtVmName. If its not set, fallback to the node name.
For openshift we have the ansible deployment, we can make sure the label is set by the ansible playbook. For Kubernetes, we need to properly document that.

**Comment by rgolangh** [comment]
Scratch all my proposes so far. I'm simply going to use the system uuid, which is the uuid of the VM in ovirt anyway. 
I can get it by running
 `oc get node node -o jsonpath='{.status.nodeInfo.systemUUID}'` 
or simpler, 
`dmidecode -s system-uuid` 

That would be the end of this saga.

**Comment by jan-zmeskal** [comment]
> `oc get node node -o jsonpath='{.status.nodeInfo.systemUUID}'`

Just out of curiosity - how does this information (VM UUID) gets propageted into OpenShift?
