### ISSUE TITLE
Missing values in vars.yaml

### ISSUE THREAD

**Issue by mircolammert** [oVirt/ovirt-openshift-extensions#112]
**Description**
In the blog post [https://ovirt.org/blog/2019/01/ovirt-openshift-part-1.html](https://ovirt.org/blog/2019/01/ovirt-openshift-part-1.html) are two Values described but missing in `ovirt-openshift-extensions/automation/ci/vars.yaml`.

The Attribute are:
- openshift_disable_check: memory_availability,disk_availability,docker_image_availability
- public_hosted_zone: example.com

Might not be a big problem but easy to fix.

**Comment by rgolangh** [comment]
Thanks for reporting.

I'll add those to the vars.yaml, the disabled checks will be commented out.
