### ISSUE TITLE
install_okd.yaml sometimes fails due to OpenShift node being unreachalbe

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-openshift-extensions#115]
**Description**
When you run install_okd.yml, the first thing it does is that it executes [openshift_ovirt role](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_ovirt). As far as I can tell, that role creates OpenShift node/s and waits for its/their IP/s. Then it continues with running setup_dns.yaml (irrelevant for this issue) and after that prerequisites.yaml are run. Here comes the issue. During the first gather_facts task in prerequisities.yaml we try to connect to newly created OpenShift node. At this point the playbook fails with "failed to connect" error, see here: http://pastebin.test.redhat.com/733411  

In our original discussion, we thought it might be caused by this: https://github.com/oVirt/ovirt-ansible-vm-infra/issues/62. However, it does not seem like it is. The referred issue deals with situation when a wrong IP is reported. If you inspect the attached pastebin, you can see that we are actually trying to a legit IP. I can confirm that it is indeed IP of OpenShift node that now can be reached via SSH. 

Also, when you immediately rerun the install_okd.yml playbook, you won't encounter the error again. Which leads to a conclusion that we are trying to use an IP reported by the engine. It provides correct info about VM's IP. However when we try to SSH, the VMs is not yet ready to accept a SSH connection.

**Steps To Reproduce**
It's basically outlined in the Description. The problem is that this is not reliably reproducible, because sometimes the playbook just passes for the first time. For the purpose of reproduction it might help to give our VM very limited resources so it takes some time until it's fully booted.

**Expected behavior**
We should wait until VM is ready to accept SSH connections. This from the first glance seems like an ideal use case for `wait_for` Ansible module: https://docs.ansible.com/ansible/latest/modules/wait_for_module.html

**Versions**
- I was using install_okd.yaml as specified in the Google doc on 7th Match 2019
- openshift-ansible-3.11.82-3.git.0.9718d0a.el7.noarch

**Logs:**
http://pastebin.test.redhat.com/733411

**Comment by rgolangh** [comment]
Probably related to the fact the the vm-infra tasks finishes with machines that have ips, but the sshd daemon is still running or something similar. 

We can try 1. a retry of the ssh connection by ansible 2. ansible wait_for_connection 3. some 'sleep' in the cloud-init
I would go with 1 or 2. The less we use cloud-init the better. If ansible can overcome that with a simple config, that its better.

```ini
[ssh_connection]
retries=2
```
or this:

```yaml
- name:
  wait_for_connection:
    timeout: 60
```

**Comment by rgolangh** [comment]
@jan-zmeskal can we close this?

**Comment by jan-zmeskal** [comment]
@rgolangh Yes, let's close this. Increasing `ANSIBLE_SSH_RETRIES` solves this just fine
