### ISSUE TITLE
oc user is switched during extensions deployment and it's left this way

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-openshift-extensions#116]
**Description**
Let's say you are logged in as `system:admin` (or any other user for that matter) in OpenShift and run extensions deployment using `docker run` and specify different `admin_user` in environment variables (e.g. `developer`) for the `ovirt-flexvolume-driver-apb` container. After the deployment is finished, you are logged in as the user you specified in the variables - `developer` in our case.

**Steps To Reproduce**
1. On master node, run this:
```
docker run  -it  --rm  --net=host  -v $HOME/.kube:/opt/apb/.kube:z  -u $UID quay.io/rgolangh/ovirt-flexvolume-driver-apb  provision -e  '{
   "admin_user":"<different user than what you are right now>",
   "admin_password":"<pass>",  
   "cluster":"openshift",
   "namespace":"default",
   "engine_username":"<user>",
   "engine_password":"<pass>",
   "engine_url":"<url>/ovirt-engine/api",
   }'
```
2. Run `oc whoami`

**Expected behavior**
After the extensions deployment, you should still be logged in as the user you originally were

**Versions:**
```
[root@master0 ~]# docker inspect quay.io/rgolangh/ovirt-flexvolume-driver-apb:latest --format='{{.ContainerConfig.Labels.version}}-{{.ContainerConfig.Labels.release}}'
0.3.2.2-11.g2192079
```

**Logs:**
http://pastebin.test.redhat.com/733938

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
