### ISSUE TITLE
It's not possible to deploy extensions without providing admin_password

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-openshift-extensions#117]
**Description**
If you want to execute `docker run` for deployment of extensions, it might happen that you want to pass `system:admin` as `admin_user` in the container's environment variables. However, that user in OpenShift does not have any password associated with it. So you have nothing to pass to `admin_password` variable. If you don't use that variable at all or if you provide an empty string there, the deployment will fail.

**Steps To Reproduce**
1. Run this:
```
docker run \
 -it \
 --rm \
 --net=host \
 -v $HOME/.kube:/opt/apb/.kube:z \
 -u $UID quay.io/rgolangh/ovirt-flexvolume-driver-apb \
 provision -e \
 '{
   "admin_user":"system:admin",
   "cluster":"openshift",
   "namespace":"default",
   "engine_username":"<user>",
   "engine_password":"<pass>",
   "engine_url":"<engine_url>",
   }'
```
2. You get this: 
```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'admin_password' is undefined\n\nThe error appears to have been in '/opt/apb/project/provision-ovirt-flexvolume-driver-apb/tasks/main.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: login\n ^ here\n"}
```

**Expected behavior**
Running deployment as `system:admin` shouldn't require `admin_password` since `system:admin` does not need any password to log in.

**Versions:**
```
[root@master0 ~]# docker inspect quay.io/rgolangh/ovirt-flexvolume-driver-apb:latest --format='{{.ContainerConfig.Labels.version}}-{{.ContainerConfig.Labels.release}}'
0.3.2.2-11.g2192079
```

Additional info:
- I don't know if we'll decide to fix this in the end. We might always require the user to use different account than `system:admin`. But I'll leave it here for our consideration.
- I created a patch that "fixes" that problem for `provision` command, see here: https://github.com/jan-zmeskal/ovirt-openshift-extensions/commit/b2159fc7973727c5f14157964007e9fcd5e96f28 The patch is ugly but IMHO it provides a good pointer about where to look in fixing this

**Comment by rgolangh** [comment]
We must have system:admin for the creation of service accounts, roles and so on

**Comment by jan-zmeskal** [comment]
@rgolangh That I understand. However, we might have OCP set up in such a way that it allows authentication of all users without password. 
For example when you specify this during OCP installation:
```
openshift_master_identity_providers=[{'mappingMethod': 'lookup', 'challenge': 'true', 'login': 'true', 'kind': 'AllowAllPasswordIdentityProvider', 'name': 'allow_all'}]
```

**Comment by rgolangh** [comment]
This is not suitable for production environments.

**Comment by jan-zmeskal** [comment]
That's of course true. However, it's good for staging envs I think. Back in the March when we were talking about this originally, I prepared a patch that suggested an easy fix of that. I cannot find it now though. It probably doesn't matter all that much since it's not in any way an essential functionality.

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
