### ISSUE TITLE
apb: compose the image name to deploy from variables

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#118]
The image registry is hardcoded in the deployment yaml, and that tag is implicitly latest. This all 
makes the deployment very static and hard to change. It makes the deployer first deploy the component and then edit the daemonset and/or the deployment config. It also causes development and QE to waste time when a deployment of specific image is needed.

The default registry would be 'quay.io' and the default tag would be 'latest'. Changing that should be
something like:

```console
docker run \
 ...
 provision -e \
 '{
   "registry": "custom.registry.io",
    "tag": "0.3.1.1-gu83jkjd",
   ...
   }'
```

**Comment by rgolangh** [comment]
@jan-zmeskal the apb image can consume even env variables now. So for the downstream image its only a matter of setting the default env variables in the Dockerfile. e.g
```Dockerfile
env FLEX_REGISTRY=foo.io
```

**Comment by jan-zmeskal** [comment]
Verified with these downstream images: http://pastebin.test.redhat.com/736558

**Comment by jan-zmeskal** [comment]
Hi @rgolangh, please remove needs-verification label or grant me the rights to manipulate labels. Thank you!
