### ISSUE TITLE
Add PV resizing support

### ISSUE THREAD

**Issue by tux-o-matic** [oVirt/ovirt-openshift-extensions#129]
Since Kuberenetes 1.8 (OpenShift 3.8), persistent volumes can be [resized](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/).
oVirt also allows [expansion](https://ovirt.org/develop/release-management/features/storage/online-virtual-drive-resize.html) of virtual disks.

This new feature would require a few new elements such as:
- Storage Class with new parameters to explicitly enable feature.
- Call the oVirt API to add XX GB to an existing virtual disk.
- Have the flex driver execute on the VM `partprobe` and appropriate `resizefs` command to do online FS resizing.

**Comment by rgolangh** [comment]
Flexvolum driver, which is the current api implemented got that feature in k 1.13 I think. Flex volume
will be maintained, but won't get new features. It is deprecated and should be replaced by CSI. Hence this #69 
I don't think I'll have the time to maintain a version of the plugin for 1.13 with resize support and #69 will solve this with CSI going GA on 1.13.

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
