### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by alclonky** [oVirt/ovirt-openshift-extensions#130]
**Description**
I tried to install extension but both ways did not work for me

**Steps To Reproduce**
- Deploy via service-catalog
  make apb_push tries to push to internal Registry IP which does not work 
  when I modify deployment/ovirt-flexvolume-driver-apb/Makefile
  and add a registry-route
  docker.io/ansibleplaybookbundle/apb-tools:latest push --registry-route <registry url>
  the push works, but Contacting the ansible-service-broker does not
  `Contacting the ansible-service-broker at: https://asb-1338-openshift-ansible-service-broker.<mydomain>/openshift-automation-service-broker/v2/bootstrap
Error: Attempt to bootstrap Broker returned status: 404
Unable to bootstrap Ansible Service Broker.
 `
- Deploy via cli
 When i run the provision step from the readme i get the following errors:
`ls: cannot open directory /etc/apb-secrets: Permission denied
Traceback (most recent call last):
  File "/usr/bin/ansible-runner", line 7, in <module>
    from ansible_runner.__main__ import main
  File "/usr/lib/python2.7/site-packages/ansible_runner/__main__.py", line 19, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2998, in <module>
    _declare_state('object', working_set = WorkingSet())
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 476, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 491, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1994, in find_on_path
    for entry in os.listdir(path_item):
OSError: [Errno 13] Permission denied: '/usr/bin'
cat: /opt/apb/artifacts/provision/rc: No such file or directory
`

**Expected behavior**
Installation works using the steps from the readme

**Versions:**
 - OS: CentOS Linux release 7.6.1810
 - Openshift|kubernetes version: okd 3.11

**Comment by rgolangh** [comment]
Can you try it with root user?

**Comment by alclonky** [comment]
was root already, 
it seams that running the `ovirt-flexvolume-driver-apb` container with `--privileged` does the trick

**Comment by rgolangh** [comment]
I never needed root and privileged together - can you add more details on how and where you run it?. But anyhow,  glad this works.

**Comment by alclonky** [comment]
I started the provision container as root on one of my master nodes (which is a normal CentOS 7.6 Installation)
