### ISSUE TITLE
Reduce size of generate image

### ISSUE THREAD

**Issue by tux-o-matic** [oVirt/ovirt-openshift-extensions#134]
I believe the driver image pulled on each node of a cluster could be made a little lighter.
- Compile Go source in same [statement](https://github.com/oVirt/ovirt-openshift-extensions/blob/master/deployment/ovirt-flexvolume-driver/container/Dockerfile#L32) where compiler is installed then finish by deleting those packages and any rpm dep (Total download size: 176 M).
- Move compiled binary [folder](https://github.com/oVirt/ovirt-openshift-extensions/blob/master/deployment/ovirt-flexvolume-driver/container/Dockerfile#L39) to */usr/bin/* as part of same *RUN* statement used previously where it got compiled.

Taking it further:
- Precompile Go code to x86 CentOS target to avoid installing and compile during Docker build steps.

**Comment by rgolangh** [comment]
@tux-o-matic looks like our CI has multi-stage support now, so hopefully this should make it much better now #136

**Comment by tux-o-matic** [comment]
Hey @rgolangh 
In https://github.com/oVirt/ovirt-openshift-extensions/commit/07f0df30f4a78fb34c0a44c5e74415d283e11417
you still install packages without remove them once Go compilation is done in deployment/ovirt-volume-provisioner/container/Dockerfile
And as used in my PR, the compiled binaries are copied in the same *RUN* as the compilation there for not leaving duplicated file sin a previous layer.
