### ISSUE TITLE
Allow specification of password in Kubernetes secret

### ISSUE THREAD

**Issue by Timoses** [oVirt/ovirt-openshift-extensions#138]
**Is your feature request related to a problem? Please describe.**
Currently, the password must be specified within the configmap. This is undesirable when storing configuration in a shared git repository.
Storing the password in a secret would for example enable using SealedSecrets.

**Describe the solution you'd like**
Extract the secret from configmap into a secret and utilize it via
* environment variable
* file or
* cmd argument

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by rgolangh** [comment]
Are you referring to the ovirt-engine password?

**Comment by Timoses** [comment]
Exactly:
https://gist.github.com/rgolangh/b8eb941ece1d7b494b232a80aabfb2d6#file-configmap-yaml

**Comment by Timoses** [comment]
As far as I can see, I've identified 3 locations where it would be important to make changes for this to work (the important function which is called at each of these is `internal.NewOvirt` https://github.com/oVirt/ovirt-openshift-extensions/blob/v0.4.0/internal/ovirt-mini-api.go#L67):

https://github.com/oVirt/ovirt-openshift-extensions/blob/v0.4.0/cmd/ovirt-cloud-provider/ovirt-cloud-provider.go#L45
https://github.com/oVirt/ovirt-openshift-extensions/blob/v0.4.0/cmd/ovirt-flexvolume-driver/ovirt-flexdriver.go#L148
https://github.com/oVirt/ovirt-openshift-extensions/blob/v0.4.0/cmd/ovirt-volume-provisioner/ovirt-provisioner.go#L97

What would you think of simply overwriting the [password](https://github.com/oVirt/ovirt-openshift-extensions/blob/v0.4.0/internal/ovirt-mini-api.go#L52) if an environment variable (e.g. `OVIRT_CONNECTION_PASSWORD`) is set and points to a file containing the password?

**Comment by rgolangh** [comment]
Seems ok I guess. Just to make it simpler I'd support a password file, then if not exist, a password ENV var. That should play standard with pod secret:
   if $OVIRT_CONNECTION_PASSWORD_FILE exists and not empty { read it }
   if $OVIRT_CONNECTION_PASSWORD  exists and non empty        { read it }
   if password in conf file not empty                                                       { read it }
   else { panic }
      
Who will take care for decrypting the SealedSecret and putting in the pod - an init container?

**Comment by Timoses** [comment]
SealedSecret-Controller will automatically populate the secret. But that is out of scope for this issue.

I've filed a PR: #145

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
