### ISSUE TITLE
Switch to go modules - drop dep

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#140]
Modernize the project and move to go modules.

The will remove a nice amount of lines of code by dropping all vendor dir.

It will also allow exposing the ovirt-mini-api to other to consume more easily.

Build times may change a bit, as it will download modules.

This must be in sync with downstream build process, and must not have any functional effect on users.

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
