### ISSUE TITLE
Install fails with Error while sending HTTP request: (7, 'Failed connect to <server>:443; Connection timed out')

### ISSUE THREAD

**Issue by alini76** [oVirt/ovirt-openshift-extensions#150]
I attempted to install the extension, but it failed with "Error while sending HTTP request: (7, 'Failed connect to <server>:443; Connection timed out')"

Steps To Reproduce
1. Connect via SSH to ovirt manager as root
2. yum install podman
3. curl -O "https://raw.githubusercontent.com/oVirt/ovirt-openshift-extensions/master/automation/ci/{install.sh,vars.yaml}"
4. Edited vars.yaml and made sure engine_insecure: true
5, run bash install.sh 

The execution fails with:
TASK [ovirt_auth] ***************************************************************************************************************************************************************************************************************************
Saturday 26 September 2020  17:08:04 +0000 (0:00:00.081)       0:00:00.081 ****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectionError: Error while sending HTTP request: (7, 'Failed connect to <server>:443; Connection timed out')
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error while sending HTTP request: (7, 'Failed connect to <server>:443; Connection timed out')"}

**Expected behavior**
I was expecting that installation ends without errors

**Versions:**
 - OS: Oracle Linux 7.8
 - Openshift|kubernetes version `oc version` or `kubectl version` - not installed yet
 - oVirt version `rpm -ql ovirt-engine`
ovirt-engine-4.3.6.6-1.0.14.el7.noarch

**Logs:**
Not sure what logs to provide

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
