### ISSUE TITLE
json: cannot unmarshal string into Go struct field Disk.actual_size of type uint64

### ISSUE THREAD

**Issue by jasonbrooks** [oVirt/ovirt-openshift-extensions#28]
I'm getting this error in the logs of my ovirt-volume-provisioner with origin 3.9 and ovirt 4.2. A bunch of disks have been created on the ovirt side but the test pod is stuck trying to mount the volume.

```
I0519 22:21:14.164887       1 controller.go:1073] scheduleOperation[provision-default/example-ovirt3[af141269-5bb1-11e8-9065-00505600010d]]
--
  | E0519 22:21:14.164897       1 controller.go:1080] Error scheduling operaion "provision-default/example-ovirt3[af141269-5bb1-11e8-9065-00505600010d]": Failed to create operation with name "provision-default/example-ovirt3[af141269-5bb1-11e8-9065-00505600010d]". An operation with that name failed at 2018-05-19 22:20:31.741167744 +0000 UTC m=+5524.466707279. No retries permitted until 2018-05-19 22:22:33.741167744 +0000 UTC m=+5646.466707279 (2m2s). Last error: "json: cannot unmarshal string into Go struct field Disk.actual_size of type uint64".
  | I0519 22:21:15.832454       1 leaderelection.go:204] stopped trying to renew lease to provision for pvc default/example-ovirt3, timeout reached
```

**Comment by rgolangh** [comment]
@jasonbrooks thanks for giving this a try!
what version is the ovirt-flexvolume-driver container?

**Comment by rgolangh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [json: cannot unmarshal string into Go struct field Disk.actual_size of type uint64 #28](https://trello.com/c/opqyn4mw/56-json-cannot-unmarshal-string-into-go-struct-field-diskactualsize-of-type-uint64-28)

**Comment by jasonbrooks** [comment]
ovirt-flexvolume-driver-v0.3.0-66_g06dbb0c.el7.centos.x86_64.rpm

  docker.io/rgolangh/ovirt-flexvolume-driver@sha256:df5980b290d5873ddd66846cbd34dcfdd1d806e0c71fbc086bcbe8f2408211ab
