### ISSUE TITLE
oVirt-engine-ui-extensions to deploy openshift with the extensions

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#65]
As an admin, I'd like to perform an openshift deployment on ovirt using the ui where I can:
- pick the vm template to be used
- pick the machine details
- specify number of nodes, master, etc, infra, app
- configurable deployment additions:
  - ovirt-openshift-extensions (flex, provisioner, cloud provider)
  - common logging (nice to have, not p1)

- All of this should use openshift-ansible rhv provider code when its ready. Meanwhile the code under automation/ci to deploy openshift will work just as well
- The ui extension code is currently a fork of https://gerrit.ovirt.org/ovirt-engine-ui-extensnions - need to decide the best place for it

**Comment by VinistoisR** [comment]
Any progress on this effort?

**Comment by rgolangh** [comment]
oVirt engine project picked this up and will create this kind of extension to install okd 3.11 with common-logging  (elasticsearch) - This means that its more than what we need, and it only needs 
few tweaks(when  ready) to fit here as well. 
I'll dig up the bugzilla or Jira ticket for it and attach it here

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
