### ISSUE TITLE
Improvement/Documentation: Add a How-To guide for installing on kubernetes

### ISSUE THREAD

**Issue by sll552** [oVirt/ovirt-openshift-extensions#68]
It would be nice to have a guide on how to install the flexvolume driver in a kubernetes environment without openshift. Currently only the openshift deployment is documented.

We are currently using oVirt and plan to run kubernetes (without openshift) on top of it.

**Comment by rgolangh** [comment]
Thanks for reporting that. 
I would like to see that happening as well but definitely would need help in doing so.

Technically, the gaps are rather small and are mainly around invoking `oc` instead of `kubectl` and few places in the [provisioning main playbook](https://github.com/oVirt/ovirt-openshift-extensions/blob/master/deployment/ovirt-flexvolume-driver-apb/roles/provision-ovirt-flexvolume-driver-apb/tasks/main.yml) would have to know to do both openshift and kubernetes.

**Comment by mjb6z9** [comment]
We have the same need as well. This looks incredibly useful for our environment.

**Comment by jagtapdeepak** [comment]
I was trying to deploy these in kuberenetes environment but not able to deploy ovirt-volume-provisioner.
ovirt-provisioner                               0/1     ErrImagePull   0          6s
Any reference document for deployment on kubernetes would be really helpful.
I can provide some help with integrating this on kuberentes.

**Comment by rgolangh** [comment]
Here is a gist with 3 files that will create the configmap, daemonset and deployment you need.
First edit the configmap with your engine details.
Then create apply the yaml's one by one, tested on Centos 7.5
https://gist.github.com/rgolangh/b8eb941ece1d7b494b232a80aabfb2d6

**Comment by rgolangh** [comment]
the ovirt vm name must be the vm name which is the compute node. The installation will take the hostname by default. So if your vm name is the same as the hostname you are all setup.

I'm adding one more Gist which is needed for the RBAC roles

**Comment by jagtapdeepak** [comment]
volume provisioner & flex volume pods got create fine but still noticing following error messages in provisioner logs.

E0103 21:57:11.381155       1 reflector.go:205] github.com/ovirt/ovirt-openshift-extensions/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:645: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:default:default" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope

**Comment by jagtapdeepak** [comment]
Thats after applying rbac-all-in-one.yaml, even before creating roles it was reporting same errors

**Comment by rgolangh** [comment]
Yes I forgot to update the ovirt-volume-provisioner deployment, it needs to have the serviceAccountName: ovirt-volume-provisioner. I'll update it.

**Comment by jagtapdeepak** [comment]
Thanks that helped! provisioner came up fine now.
Ran example/test-flex-pod-all-in-one.yaml it created pv on the storage domain but for  did not attach pv disk to vm. May be issue with my cluster as one vmname does not match hostname for the master node.
One more thing noticed is that provisioner always getting created on worker node and not master node, will that cause an issue?

**Comment by rgolangh** [comment]
You examine the journal on the worker node to see if the flexvolume is returning any error. If the VM name is ther problem you can tweak that in `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/ovirt~ovirt-flexvolume-driver/ovirt-flexvolume-driver.conf` 
I think I need to provide a better way to get the vm name, possibly by queriying a label on the node.
Feel free to open an issue on that if you think that's relevant to your setup, and you too need a more robust solution for the vm name mapping.

Deploying the proivisioner on a compute node seems ok, event though controller like that do belong to the master. Its generally not a problem. I can schedule it on master by a label I guess.

**Comment by jagtapdeepak** [comment]
After recreating kube cluster with correct vmname to hostname mapping it worked. pod got created with pv attached. I also have to add following in provisioner.yaml and flexvolume.yaml so that pods can access ovirt-manager fqdn:
      dnsConfig:
        nameservers:
         - my-dns-server-ip
Appreciate your help...this is great stuff!

**Comment by rgolangh** [comment]
Help needed with creating a small wiki from  this [gist](https://gist.github.com/rgolangh/b8eb941ece1d7b494b232a80aabfb2d6) and explaining how to use it. @jagtapdeepak will you have few minutes to contribute that?

**Comment by jagtapdeepak** [comment]
Sure @rgolangh will add the wiki sometime this week. Should I just update README with section for Kubernetes?

**Comment by rgolangh** [comment]
Depends how long it is. I think we can create an installation readme, and link it from the root README

**Comment by jagtapdeepak** [comment]
@rgolangh I was thinking of adding following as part of  Deployment-on-kubernetes.md in the wiki.
But for some reason couldn't push the changes either in  wiki master or separate branch.

git push origin kubewiki
Username for 'https://github.com': jagtapdeepak
Password for 'https://jagtapdeepak@github.com': 
remote: Permission to oVirt/ovirt-openshift-extensions.wiki.git denied to jagtapdeepak.
Whats the process you generally follow for updating wiki? How to get it reviewed before committing?

Please let me know if following  text should be enough to start with:

Volume provisioner and flexvolume driver can easily be deployed on kubernetes cluster.
Following document explains quick steps to deploy ovirt-openshift-extensions on kubernetes enviroment.

Deployment
-----------
1. Checkout sample deployment yaml's from https://gist.github.com/rgolangh/b8eb941ece1d7b494b232a80aabfb2d6

2. Update configmap.yaml to provide your ovirt connections details. Mainly you need to modify url, password fields in the configmap.yaml
   Create config map by:
   kubectl create -f configmap.yaml

3. Create cluster role, role bindings & service account required for volume provisioner and flexvoume driver.
   kubectl create -f rbac-all-in-one.yaml

4. Create volume provisoner deployment.
   kubectl create -f provisioner.yaml
   Confirm that ovirt-volume-provisioner pod is scheduled and up by running `kubectl get pods`.

5. Deploy flexvolume driver on all compute nodes by running following on the master node.
   kubectl create -f flexvolume.yaml
   You can confirm that ovirt-flexvolume-driver pod is scheduled and up on all `kubernetes get pods`.

   Please check the logs for provisioner &  flexvolume-driver pods to confirm it can access ovirt url using 'kubectl get logs YOUR-POD-NAME'.
   If  kubenetes compute node has problem accessing ovirt engine url, you might need to tweak your kubernetes cluster 
   network configs or provide custom dns settings in flexvoume.yaml & provisoner.yaml and recreate them.
   
   ``` 
   dnsConfig:
     nameservers:
       - YOUR-DNS-SERVER-IP
   ```

Now your kubernetes cluster is ready to provision volumes from ovirt.


Test
------
Test your cluster by checking out https://github.com/oVirt/ovirt-openshift-extensions/blob/master/deployment/example/test-flex-pod-all-in-one.yaml
Update ovirtStorageDomain field in test-flex-pod-all-in-one.yaml file to refer to your ovirt storage domain name on which
volume needs to be provisioned.

Then spin off testpodwithflex by running
kubectl create -f test-flex-pod-all-in-one.yaml

Verify that volume is provisioned on your strorage domain and it's attached compute node where testpodwithflex is scheduled.

Enjoy your setup. Your feedback and contributions are most welcome.

**Comment by rgolangh** [comment]
@jagtapdeepak I really appreciate this, thanks a lot. 
To ease up the contribution I created the docs folder. It totally replaces the wiki, more standard and is really a part of the project. (maybe I'll even enable github pages on it)
So just try to create a regular pull request with your md file add to here https://github.com/oVirt/ovirt-openshift-extensions/tree/master/docs
