### ISSUE TITLE
Port flexvolume driver to a CSI driver

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#69]
CSI is the upcoming storage driver interface, went beta in kubernetes 1.10,  being tech-preview in opneshift 3.10 and 3.11.
Flex is  not deprecated officially although CSI is targeted to be the only supported external storage extension point.

Goals:
- A CSI implementation can replace the flex implementation without regressions, as is seems and that includes:
  - provision a disk on the external storage provider using the controller (vs storage provisioner for flex)
  - attach/detach the disk to the node (the VM)
  - mount/unmount (or stage and publish in CSI terminology), format the disk and mount it 
- Share as much code as possible between csi and flex. E.g, a fix in the way we prepare the filesystem will most surely be needed for both.

Non-Goals:
- Snapshots support - exists in current csi spec. This feature is anyhow missing in Flex, and is out of the scope for this issue.
- Migration from flex to csi.

This implementation will yield 2 containers, a node plugin and a controller plugin, which is synonimous to flexvolume-driver, and volume-provisioner components of flex.
The deployment is similar as well, a daemon-set to deploy the node-plugin on all nodes, and a deployment of a single controller-plugin (replica set of 1).

CSI spec: https://github.com/container-storage-interface/spec
CSI goes beta: https://kubernetes.io/blog/2018/04/10/container-storage-interface-beta/
CSI test package: https://github.com/kubernetes-csi/csi-test

**Comment by cobexer** [comment]
Is there already progress on this?

**Comment by rgolangh** [comment]
Didn't start to work on yet s I have other stuff with higher priority. 

Maybe a short poll:
- users don't use persistent volumes from oVirt because they wait for CSI please add :+1:

**Comment by rgolangh** [comment]
The implementation is now under its own repo https://github.com/ovirt/csi-driver
