### ISSUE TITLE
provisioner: renew token doesn't work on the provisioner container

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#7]
This is a bug of the ovirt-mini-api which affects the provisioner, as a long running service. (the flex driver is invoked and then tears down)
oVirt engine is holding the token as long as it is up and dump them if it restarts. This means that a client
such as the provisioner would get request failing without ever handling it, leaving it unusable untill the provisioner pod is restarted, and then it will negotiate for a new ticktet.

The handling should be straight forward, if identifying a non valid token response is a distinct error. In that case, simply tell the api to refetch a token.

**Comment by fifthecho** [comment]
I've encountered this in my oVirt/K8S pilot and would love for a graceful way to have the token be refreshed.

**Comment by rgolangh** [comment]
On Thu, 8 Mar 2018 at 20:54 Jeff Moody <notifications@github.com> wrote:

> I've encountered this in my oVirt/K8S pilot and would love for a graceful
> way to have the token be refreshed.
>
> —
>
This will be fixed this week.

**Comment by rgolangh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [token doesn't auto renew on expiration or invalidation](https://trello.com/c/pCwgK3mS/38-token-doesnt-auto-renew-on-expiration-or-invalidation)

**Comment by rgolangh** [comment]
A request with non-existing token is replying with 401 and with specific text:
```
 curl http://localhost:8080/ovirt-engine/api \
   -H "Accept: application/json" \
   -H "Authorization: Bearer NONEXISTINGTOKEN"  -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /ovirt-engine/api HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.55.1
> Accept: application/json
> Authorization: Bearer NONEXISTINGTOKEN
>
< HTTP/1.1 401 Unauthorized
< Connection: keep-alive
< WWW-Authenticate: Basic realm="RESTAPI"
< Content-Type: text/html;charset=UTF-8
< Content-Length: 137
< Date: Mon, 19 Mar 2018 09:14:49 GMT
< 
* Connection #0 to host localhost left intact
<html><head><title>Error</title></head><body>invalid_grant: The provided authorization grant for the auth code has expired.</body></html>
```
