### ISSUE TITLE
Add health check and/or liveliness checks

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#77]
This is a meta issue for health and liveliness checks for all components.

As an admin I want to make sure I know what's the status of each component.
Verify that I know when a component is fully operational
Verify that I know when a component is not operational
Verify I know when ovirt tokens are missing/expired (i.e I know when failed login occurs and I get to know that to remedy it - change password etc...)

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
