### ISSUE TITLE
Specify ovirt-cloud-provider in openshift-ovirt role

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#78]
**Is your feature request related to a problem? Please describe.**
openshift-ovirt role in openshift-ansible should useovirt-cloud-provider by default

**Describe the solution you'd like**
As an admin I'd like to install openshift on ovirt and include ovirt's cloud provider by default.
This implies `openshift_cloudprovider_kind=ovirt-cloud-provider' (name is still not final)

This can be excluded by nullifying the variable `openshift_cloudprovider_kind=`

**Comment by sandrobonazzola** [comment]
This project is no longer maintained, closing.
