### ISSUE TITLE
Document the ovirt user permission setup

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-openshift-extensions#89]
**Description**
We don't want users to set the ovirt's super user admin for the various actions the extensions are/
running. We should document what are the needed permissions a user needs to have.

As an oVirt and OCP admin I'd like to provision a user with the permission needed for the various actions the extensions needs to perform.

| K8s component |  Action | Object | oVirt Role | 
| -- | -- | -- | -- |
| Volume provisioner | Create Disk | Storage Domain/DC | **StorageAdmin** on the designated domain or DC |
| Flex driver | Attach/Detach Disk  | VMs on cluster/DC  | **StorageAdmin** on the designated domain or DC | 

**Expected behavior**
A clear description with example of how to create such a user.

**Comment by rgolangh** [comment]
The best practice would be to grant a user the **StorageAdmin** **role**, on the data-center where Openshift or K8s will be deployed. For finer-grained control the role can be granted on a specific data domain where all the claims should use.

**Comment by rgolangh** [comment]
Added a wiki page with a playbook to create and configure the user.

https://github.com/oVirt/ovirt-openshift-extensions/wiki/Creating-an-oVirt-user---how-to

**Comment by jan-zmeskal** [comment]
Great work, thank you for this!
