### ISSUE TITLE
Listing ovirt-volume-provisioner's logs takes huge amount of time after some uptime

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-openshift-extensions#92]
**Description**
If you call `oc logs -f` on ovirt-volume-provisioner after it's been running for some days, it takes 15+ seconds to scroll to the bottom of log entry and this can get quite annoying.

The question is what we can do about this. This need some research. Maybe we should rotate logs after some time period.

**Comment by rgolangh** [comment]
That's in the domain of deployment logging handling. Generally, if the the container runtime is *docker* then you need to set that in the docker daemon setting [1] or by *crio* logsize [2] 
[1] https://docs.openshift.com/container-platform/3.5/install_config/install/host_preparation.html#managing-docker-container-logs
[2] https://github.com/kubernetes-sigs/cri-o/blob/master/docs/crio.8.md

I'd like to close this unless you have something to add?

**Comment by jan-zmeskal** [comment]
I think we can close, thanks for the investigation!
